/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/graphikxTheme.ts
 * Command: astryx theme build src/theme/graphikxTheme.ts --out src/theme/graphikx.css
 * CLI: @astryxdesign/cli@0.6.4
 * Core: @astryxdesign/core@0.6.4
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const graphikxTheme: DefinedTheme;
